train_data_dir: action_class/data_path/data/train
valid_data_dir: action_class/data_path/data/valid
test_data_dir: action_class/data_path/data/test
csv_logger_dir: action_class/data_path/logger
tensorboard_logger_dir: action_class/data_path/logger/tensorboard_logger
checkpoint_dir: action_class/data_path/model/checkpoint
final_model_dir: action_class/data_path/model
output_stream_logger_file: action_class/data_path/logger/logger_info.txt
imagenet_file: action_class/data_path/model/imagenet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
batch_size: 32
learning_rate: .001
epoch: 20
input_image_shape: [256, 256, 3]
checkpoint_model_name: ep{epoch:03d}-loss{loss:.3f}-val_loss{val_loss:.3f}.h5